Добавляет 2 функции
htmlacademy-javascript/1955797-kekstagram-25 pull request #2
Opened 2022-02-20 07:24 UTC by semenbushmanov

Для написания функций использовал:
1) https://www.geeksforgeeks.org/how-to-generate-random-number-in-given-range-using-javascript/
2) https://www.w3schools.com/js/js_math.asp
3) https://www.w3schools.com/js/js_type_conversion.asp

2022-02-20 17:23 UTC, MrMeison requested changes

2022-02-20 17:23 UTC, MrMeison commented on js/main.js
> +  const commentLength = String(commentString).length;
Можно сильно проще как 
`return commentString.length > maxLength;`
условие само по себе возращает булево значение.

2022-02-20 17:23 UTC, MrMeison commented on js/main.js
> +  min = Math.ceil(Math.abs(min));
Похвально что ты делаешь максимально гибкие функции! Но точно ли такая гибкость нужна? Вполне возможно будет достаточно только последней строки функции.

2022-02-22 06:28 UTC, semenbushmanov commented on js/main.js
> +  const commentLength = String(commentString).length;
Для меня это было удивительно, но действительно после анализа и проверок с разными параметрами работает! Правда я еще, сделал так, чтобы комментарий с максимальной длиной тоже давал значение true: commentString.length <= maxLength.

2022-02-22 06:30 UTC, semenbushmanov commented on js/main.js
> +  min = Math.ceil(Math.abs(min));
Оказалось, что все работает также и с одной строкой функции - получается был избыточный код. Спасибо!

2022-02-22 08:52 UTC, merged