Module5 task1
htmlacademy-javascript/1955797-kekstagram-25 pull request #4
Opened 2022-03-06 14:33 UTC by semenbushmanov

Разделил код на модули, подключил их, сделал refactoring.

2022-03-07 09:40 UTC, MrMeison requested changes

2022-03-07 09:40 UTC, MrMeison commented on js/data.js
> +const DESCRIPTION_SET = [
```suggestion
const DESCRIPTIONS = [
```

2022-03-07 09:40 UTC, MrMeison commented on js/data.js
> +const getRandomArrayElement = (elements) => elements[getRandomNumber(0, elements.length - 1)];
```suggestion
const getRandomItem = (items) => elements[getRandomNumber(0, elements.length - 1)];
```

2022-03-07 09:40 UTC, MrMeison commented on js/data.js
> +  for (let i = 1; i <= 3; i++) {
Вынести в константы

2022-03-07 09:40 UTC, MrMeison commented on js/data.js
> +const getComments = (photoNumber) => {
```suggestion
const createComments = (photoNumber) => {
```

2022-03-07 09:40 UTC, MrMeison commented on js/data.js
> +const createDescription = (photoNumber) => ({
```suggestion
const createPhoto = (photoNumber) => ({
```

2022-03-07 09:40 UTC, MrMeison commented on js/data.js
> +const createPhotoDescriptionSet = (count) => {
```suggestion
const createPhotos = (count) => {
```

2022-03-07 09:40 UTC, MrMeison commented on js/util.js
> +const isCommentLengthCorrect = (commentString, maxLength) => commentString.length <= maxLength;
```suggestion
const checkLength = (string, maxLength) => commentString.length <= maxLength;
```

2022-03-08 06:14 UTC, semenbushmanov commented on js/data.js
> +const getRandomArrayElement = (elements) => elements[getRandomNumber(0, elements.length - 1)];
Появилась мысль: а может эту функцию в js/util.js перенести?

2022-03-09 17:20 UTC, semenbushmanov commented on js/data.js
> +  for (let i = 1; i <= 3; i++) {
Константу кол-во комментариев к фото поставил прямо перед функцией. Может ее вообще как параметр в функцию передавать?

2022-03-09 17:20 UTC, semenbushmanov commented on js/data.js
> +const getComments = (photoNumber) => {
Полностью согласен!

2022-03-09 20:08 UTC, merged