add full size photo rendering
htmlacademy-javascript/1955797-kekstagram-25 pull request #6
Opened 2022-03-21 11:04 UTC by semenbushmanov

Все работает как надо, но eslint ругается, что в файле full-size-image.js в функции onImageEscKeydown была использована функция closeFullSizeImage до того, как она была определена. Пока проигнорировал, так как в демонстрации учебного проекта была такая же ситуация.

2022-03-21 14:53 UTC, semenbushmanov commented
Исправил код, все проверки проходит. К сожалению при нажатии на клавишу Escape в полноэкранном режиме не удаляется обработчик событий, навешанный на крестик в правом верхнем углу фото.

2022-03-22 07:14 UTC, MrMeison requested changes

2022-03-22 07:14 UTC, MrMeison commented on js/full-size-image.js
> +const bigPictureImage = document.querySelector('.big-picture__img img');
здесь лучше искать не в `document`, а непосредственно в `bigPicture`, чтобы локализовать поиск

2022-03-22 07:14 UTC, MrMeison commented on js/full-size-image.js
> +  closeButton.removeEventListener('click', onCloseButtonClick);
этот обработчик как раз можно не удалять — окно просмотра у тебя никогда не удаляется и можно дополнительно не вышать обратчики.

2022-03-22 07:14 UTC, MrMeison commented on js/full-size-image.js
> +  document.removeEventListener('keydown', onImageEscKeydown);
Удаление обработчика закрытия по `esc` лучше вынести в функцию закрытия, т.к. при увеличении способов закрытия попапа у тебя будет всегда дублироваться этот код

2022-03-22 08:25 UTC, semenbushmanov commented on js/full-size-image.js
> +const bigPictureImage = document.querySelector('.big-picture__img img');
Точно! Когда на черновике наброски делал это учитывал, потом забыл.

2022-03-22 10:51 UTC, semenbushmanov commented on js/full-size-image.js
> +  document.removeEventListener('keydown', onImageEscKeydown);
Хорошо!

2022-03-22 11:28 UTC, merged