Module8 task1
htmlacademy-javascript/1955797-kekstagram-25 pull request #7
Opened 2022-03-29 10:47 UTC by semenbushmanov

Проверял в браузере, загрузка и валидация работает. Чтобы решить задачу в последнем коммите: "если фокус находится в поле ввода хэш-тега, нажатие на Esc не должно приводить к закрытию формы редактирования изображения", списал идею проверки условия у однокурсника в чате Discord.

2022-03-29 18:11 UTC, MrMeison requested changes

2022-03-29 18:11 UTC, MrMeison commented on js/validation.js
> +const validateHashtags = (hashtagText) => {
Я бы разбил эту валидацию на 3 отдельных, чтобы пользователь сразу понимал что не так.
Кстати тут пригодится свойство `halt` при добавлении валидатора, чтобы показывать только первую ошибку

2022-03-29 18:11 UTC, MrMeison commented on js/validation.js
> +const validateForm = () => {
Если подумать, то такое название тут не очень подходит. Ведь эта функция не "валидирует форму", а "инициализирует валидацию"

2022-03-29 18:11 UTC, MrMeison commented on js/validation.js
> +    const hashtagCheck = re.test(hashtag);
можно сразу написать в `if`

2022-03-30 07:46 UTC, semenbushmanov commented on js/validation.js
> +    const hashtagCheck = re.test(hashtag);
Понял идею. Думаю улучшить - решил сократить код и применил в этом случае метод массивов "array.every()".

2022-03-30 07:48 UTC, semenbushmanov commented on js/validation.js
> +const validateForm = () => {
Действительно так. Выбираю название между startValidation() и subscribeToFormValidation. По итогу выбрал 2 вариант.

2022-03-30 07:51 UTC, semenbushmanov commented on js/validation.js
> +const validateHashtags = (hashtagText) => {
Разбил на 3. Вынес в отдельную функцию создание массива из текста поля хэштегов. Добавил приоритет валидаторам и установил флаг true в свойстве halt.

2022-03-30 08:11 UTC, merged