Module9 task1
htmlacademy-javascript/1955797-kekstagram-25 pull request #9
Opened 2022-04-05 10:45 UTC by semenbushmanov

Добавил модули масштабирования и редактирования фото при загрузке.

2022-04-05 14:59 UTC, MrMeison requested changes

2022-04-05 14:59 UTC, MrMeison commented on js/full-size-image.js
> +  commentsToRenderCount = 5;
Вынеси в константы пожалуйста

2022-04-05 14:59 UTC, MrMeison commented on js/scale.js
> +    scale += 25;
тоже в константы

2022-04-05 14:59 UTC, MrMeison commented on js/validation.js
> +  return hashtags.length <= 5;
ну ты понял :)

2022-04-06 06:54 UTC, semenbushmanov commented on js/full-size-image.js
> +  commentsToRenderCount = 5;
Хорошо!

2022-04-06 06:57 UTC, semenbushmanov commented on js/scale.js
> +    scale += 25;
Постарался убрать все волшебные непонятные числа из кода. Читать стало понятнее!

2022-04-06 07:35 UTC, merged